version: '3.1'
services:
    db:
        image: postgres
        restart: always
        volumes:
            - /private/var/lib/postgresql:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=fxdata
            - POSTGRES_PASSWORD
            - POSTGRES_DB=fxdata
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
          - .:/myapp
        ports:
          - "3000:3000"
        depends_on:
          - db
#run
#docker swarm init
#POSTGRES_PASSWORD=mysecret docker stack deploy -c stack.yml fx-data

#connect to db from another window:
#psql -h localhost -U fxdata fxdatasecret
