FROM ruby:2.3.4
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash && apt-get install -y nodejs
RUN mkdir -p /app
WORKDIR /app
COPY . ./
ARG RAILS_ENV=production
ENV RAILS_ENV $RAILS_ENV
RUN npm install
RUN npm run webpack
RUN if [ "$RAILS_ENV" = "production" ] ; then echo "production env" && gem install bundler && bundle install --without development test development_scraper production_scraper ; else echo "non-production env $RAILS_ENV" && gem install bundler && bundle install --without development_scraper production_scraper ; fi
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
