version: '3.1'
services:
    db:
        image: postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
            args:
                - RAILS_ENV=${RAILS_ENV:-production}
        image: joshweir/fxdata-stack/web:${FXDATA_VERSION:-latest}
        command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        restart: always
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - RAILS_ENV=${RAILS_ENV:-production}
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
    recurring-tasks:
        build:
            context: .
            dockerfile: Dockerfile.recurring_tasks
            args:
                - RAILS_ENV=${RAILS_ENV:-production}
        image: joshweir/fxdata-stack/recurring-tasks:${FXDATA_VERSION:-latest}
        command: bundle exec /app/lib/tasks/recurring_tasks.rb
        restart: always
        stdin_open: true
        tty: true
        depends_on:
            - db
        environment:
            - RAILS_ENV=${RAILS_ENV:-production}
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
volumes:
    db-data:

#proposed:
#dev:
#docker-compose build
#docker-compose up
#to create db or migrate
#docker-compose run web rake db:create
#docker-compose run web rake db:migrate

#prod:
#build and push:
#export RAILS_ENV=production
#optionally specify the version of the stack to build/push (defaults to latest):
#export FXDATA_VERSION=0.1.0
#docker-compose -f docker-compose.yml build
#docker-compose -f docker-compose.yml push
#deploy:
#export RAILS_ENV=production
#optionally specify the version of the stack to build/push (defaults to latest):
#export FXDATA_VERSION=0.1.0
#docker swarm init
#docker stack deploy fxdata-stack -f docker-compose.yml --with-registry-auth
#to create db or migrate
#docker-compose -f docker-compose.yml run web rake db:create
#docker-compose -f docker-compose.yml run web rake db:migrate

#connect to db from another window:
#psql -h localhost -U <user> <pass>
