FROM ruby:2.3.4

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir -p /app
WORKDIR /app

ADD Gemfile .
ADD Gemfile.lock .

RUN gem install bundler && bundle install --without development test

COPY . ./

ENV RAILS_ENV production

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
