#FROM ruby:2.3.4-alpine
FROM ruby:2.3.4

#RUN apk add --update --no-cache build-base ruby-dev tzdata postgresql-dev \
# nodejs
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash && apt-get install -y nodejs

RUN mkdir -p /app
WORKDIR /app

#ADD Gemfile .
#ADD Gemfile.lock .
ADD . ./

RUN npm install
RUN npm run webpack
RUN gem install sigar -- --with-cppflags="-fgnu89-inline"
RUN gem install bundler && bundle install

#COPY . ./

ENV RAILS_ENV development

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
